import { Volunteer, Zone, Incident, Assignment, Notification, ActivityFeedItem, DemoScenario } from '@/types';
import { v4 as uuidv4 } from 'uuid';

// ============================================================
// Zones — 10 Mahakumbh zones
// ============================================================
export const DEMO_ZONES: Zone[] = [
  {
    id: 'z-01',
    zone_name: 'Sangam Ghat',
    zone_code: 'Z01',
    description: 'Primary bathing ghat at the Triveni Sangam — highest footfall zone',
    required_skills: ['crowd_management', 'medical', 'emergency_response'],
    current_volunteer_count: 23,
    required_volunteer_count: 50,
    risk_level: 'critical',
    crowd_density: 'extreme',
    latitude: 25.4261,
    longitude: 81.8838,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-02',
    zone_name: 'Ram Ghat',
    zone_code: 'Z02',
    description: 'Secondary bathing area with high pilgrim traffic',
    required_skills: ['crowd_management', 'information_desk', 'traffic_coordination'],
    current_volunteer_count: 28,
    required_volunteer_count: 35,
    risk_level: 'high',
    crowd_density: 'very_high',
    latitude: 25.4302,
    longitude: 81.8801,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-03',
    zone_name: 'Triveni Crossing',
    zone_code: 'Z03',
    description: 'Critical junction — traffic bottleneck during peak hours',
    required_skills: ['traffic_coordination', 'crowd_management', 'emergency_response'],
    current_volunteer_count: 18,
    required_volunteer_count: 40,
    risk_level: 'critical',
    crowd_density: 'extreme',
    latitude: 25.4271,
    longitude: 81.8821,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-mc1',
    zone_name: 'Medical Camp Alpha',
    zone_code: 'MC1',
    description: 'Primary medical facility with triage and emergency care',
    required_skills: ['medical', 'first_aid', 'emergency_response', 'cpr'],
    current_volunteer_count: 19,
    required_volunteer_count: 25,
    risk_level: 'high',
    crowd_density: 'moderate',
    latitude: 25.4325,
    longitude: 81.8756,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-mc2',
    zone_name: 'Medical Camp Beta',
    zone_code: 'MC2',
    description: 'Secondary medical post for minor injuries and first aid',
    required_skills: ['medical', 'first_aid', 'nursing'],
    current_volunteer_count: 16,
    required_volunteer_count: 20,
    risk_level: 'medium',
    crowd_density: 'moderate',
    latitude: 25.4388,
    longitude: 81.8690,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-lf1',
    zone_name: 'Lost & Found Center',
    zone_code: 'LF1',
    description: 'Central hub for missing persons, lost items, and family reunification',
    required_skills: ['information_desk', 'communication', 'multilingual'],
    current_volunteer_count: 12,
    required_volunteer_count: 15,
    risk_level: 'low',
    crowd_density: 'moderate',
    latitude: 25.4410,
    longitude: 81.8620,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-g01',
    zone_name: 'Main Entry Gate',
    zone_code: 'G01',
    description: 'Primary entry checkpoint — high inflow during bathing schedules',
    required_skills: ['crowd_management', 'traffic_coordination', 'security'],
    current_volunteer_count: 22,
    required_volunteer_count: 30,
    risk_level: 'high',
    crowd_density: 'very_high',
    latitude: 25.4450,
    longitude: 81.8580,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-pk1',
    zone_name: 'Parking Zone A',
    zone_code: 'PK1',
    description: 'Main vehicle parking management and traffic flow',
    required_skills: ['traffic_coordination', 'vehicle_management'],
    current_volunteer_count: 17,
    required_volunteer_count: 20,
    risk_level: 'low',
    crowd_density: 'high',
    latitude: 25.4480,
    longitude: 81.8540,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-vip',
    zone_name: 'VIP Enclosure',
    zone_code: 'VIP',
    description: 'Restricted area for dignitaries, saints, and official guests',
    required_skills: ['protocol', 'information_desk', 'emergency_response', 'communication'],
    current_volunteer_count: 13,
    required_volunteer_count: 15,
    risk_level: 'medium',
    crowd_density: 'low',
    latitude: 25.4290,
    longitude: 81.8870,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'z-fd1',
    zone_name: 'Food Distribution Hub',
    zone_code: 'FD1',
    description: 'Langar and food distribution center for pilgrims',
    required_skills: ['food_distribution', 'crowd_management', 'hygiene_management'],
    current_volunteer_count: 20,
    required_volunteer_count: 25,
    risk_level: 'low',
    crowd_density: 'high',
    latitude: 25.4360,
    longitude: 81.8720,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

// ============================================================
// Volunteers — 30 realistic Mahakumbh volunteers
// ============================================================
export const DEMO_VOLUNTEERS: Volunteer[] = [
  {
    id: 'v-01',
    name: 'Dr. Rajesh Sharma',
    email: 'rajesh.sharma@mahasahayak.com',
    phone: '+91-9876543210',
    age: 42,
    skills: ['medical', 'first_aid', 'emergency_response', 'cpr', 'triage'],
    languages: ['hindi', 'english'],
    experience_level: 'expert',
    availability: 'available',
    assigned_zone: 'z-mc1',
    workload_score: 35,
    bharat_ready_score: 94,
    hours_worked: 4.5,
    active_assignments: 1,
    latitude: 25.4325,
    longitude: 81.8756,
    status: 'active',
  },
  {
    id: 'v-02',
    name: 'Nurse Priya Verma',
    email: 'priya.verma@mahasahayak.com',
    age: 29,
    skills: ['medical', 'first_aid', 'nursing', 'cpr'],
    languages: ['hindi', 'english', 'bhojpuri'],
    experience_level: 'expert',
    availability: 'available',
    assigned_zone: 'z-mc1',
    workload_score: 40,
    bharat_ready_score: 89,
    hours_worked: 5.0,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-03',
    name: 'Dr. Anita Mishra',
    age: 36,
    skills: ['medical', 'triage', 'emergency_response'],
    languages: ['hindi', 'english'],
    experience_level: 'expert',
    availability: 'busy',
    assigned_zone: 'z-mc2',
    workload_score: 78,
    bharat_ready_score: 91,
    hours_worked: 8.0,
    active_assignments: 2,
    status: 'active',
  },
  {
    id: 'v-04',
    name: 'Vikram Pandey',
    age: 24,
    skills: ['first_aid', 'cpr'],
    languages: ['hindi', 'bhojpuri'],
    experience_level: 'intermediate',
    availability: 'available',
    workload_score: 20,
    bharat_ready_score: 67,
    hours_worked: 2.0,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-05',
    name: 'Suresh Kumar Yadav',
    age: 38,
    skills: ['crowd_management', 'emergency_response', 'security'],
    languages: ['hindi', 'bhojpuri'],
    experience_level: 'expert',
    availability: 'available',
    assigned_zone: 'z-01',
    workload_score: 45,
    bharat_ready_score: 88,
    hours_worked: 6.0,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-06',
    name: 'Ramesh Gupta',
    age: 44,
    skills: ['crowd_management', 'traffic_coordination', 'security'],
    languages: ['hindi', 'english'],
    experience_level: 'expert',
    availability: 'on_break',
    assigned_zone: 'z-02',
    workload_score: 82,
    bharat_ready_score: 85,
    hours_worked: 9.0,
    active_assignments: 2,
    status: 'active',
  },
  {
    id: 'v-07',
    name: 'Anjali Singh',
    age: 26,
    skills: ['crowd_management', 'information_desk'],
    languages: ['hindi', 'english', 'maithili'],
    experience_level: 'intermediate',
    availability: 'available',
    assigned_zone: 'z-02',
    workload_score: 30,
    bharat_ready_score: 72,
    hours_worked: 3.5,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-08',
    name: 'Mohit Tiwari',
    age: 22,
    skills: ['crowd_management', 'communication'],
    languages: ['hindi'],
    experience_level: 'beginner',
    availability: 'available',
    workload_score: 15,
    bharat_ready_score: 55,
    hours_worked: 1.5,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-09',
    name: 'Inspector Deepak Joshi',
    age: 41,
    skills: ['traffic_coordination', 'crowd_management', 'security'],
    languages: ['hindi', 'english'],
    experience_level: 'expert',
    availability: 'available',
    assigned_zone: 'z-g01',
    workload_score: 55,
    bharat_ready_score: 90,
    hours_worked: 7.0,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-10',
    name: 'Pooja Tiwari',
    age: 28,
    skills: ['traffic_coordination', 'vehicle_management'],
    languages: ['hindi', 'english'],
    experience_level: 'intermediate',
    availability: 'available',
    assigned_zone: 'z-pk1',
    workload_score: 25,
    bharat_ready_score: 70,
    hours_worked: 3.0,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-11',
    name: 'Ritu Agarwal',
    age: 31,
    skills: ['information_desk', 'communication', 'multilingual'],
    languages: ['hindi', 'english', 'bengali', 'gujarati'],
    experience_level: 'expert',
    availability: 'available',
    assigned_zone: 'z-lf1',
    workload_score: 38,
    bharat_ready_score: 86,
    hours_worked: 5.0,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-12',
    name: 'Sanjay Mehta',
    age: 27,
    skills: ['information_desk', 'communication', 'lost_and_found'],
    languages: ['hindi', 'english', 'marathi'],
    experience_level: 'intermediate',
    availability: 'busy',
    assigned_zone: 'z-lf1',
    workload_score: 72,
    bharat_ready_score: 74,
    hours_worked: 7.5,
    active_assignments: 2,
    status: 'active',
  },
  {
    id: 'v-13',
    name: 'Kavita Sharma',
    age: 33,
    skills: ['information_desk', 'multilingual', 'communication'],
    languages: ['hindi', 'english', 'punjabi', 'urdu'],
    experience_level: 'expert',
    availability: 'available',
    assigned_zone: 'z-vip',
    workload_score: 28,
    bharat_ready_score: 83,
    hours_worked: 3.5,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-14',
    name: 'Arjun Pathak',
    age: 29,
    skills: ['emergency_response', 'first_aid', 'crowd_management'],
    languages: ['hindi', 'english'],
    experience_level: 'intermediate',
    availability: 'available',
    assigned_zone: 'z-01',
    workload_score: 42,
    bharat_ready_score: 78,
    hours_worked: 5.5,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-15',
    name: 'Neha Dubey',
    age: 25,
    skills: ['emergency_response', 'cpr', 'first_aid'],
    languages: ['hindi', 'bhojpuri'],
    experience_level: 'intermediate',
    availability: 'available',
    workload_score: 18,
    bharat_ready_score: 71,
    hours_worked: 2.0,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-16',
    name: 'Rahul Chaudhary',
    age: 20,
    skills: ['crowd_management', 'food_distribution'],
    languages: ['hindi'],
    experience_level: 'beginner',
    availability: 'available',
    workload_score: 10,
    bharat_ready_score: 48,
    hours_worked: 1.0,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-17',
    name: 'Ananya Srivastava',
    age: 21,
    skills: ['information_desk', 'communication'],
    languages: ['hindi', 'english'],
    experience_level: 'beginner',
    availability: 'available',
    workload_score: 12,
    bharat_ready_score: 52,
    hours_worked: 1.5,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-18',
    name: 'Deepak Maurya',
    age: 22,
    skills: ['food_distribution', 'crowd_management'],
    languages: ['hindi', 'bhojpuri'],
    experience_level: 'beginner',
    availability: 'available',
    workload_score: 8,
    bharat_ready_score: 45,
    hours_worked: 0.5,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-19',
    name: 'Col. Vijay Rawat (Retd)',
    age: 55,
    skills: ['crowd_management', 'emergency_response', 'security', 'traffic_coordination'],
    languages: ['hindi', 'english'],
    experience_level: 'expert',
    availability: 'busy',
    assigned_zone: 'z-01',
    workload_score: 91,
    bharat_ready_score: 96,
    hours_worked: 10.5,
    active_assignments: 3,
    status: 'active',
  },
  {
    id: 'v-20',
    name: 'Dr. Sunita Tripathi',
    age: 39,
    skills: ['medical', 'triage', 'emergency_response', 'nursing'],
    languages: ['hindi', 'english'],
    experience_level: 'expert',
    availability: 'busy',
    assigned_zone: 'z-mc1',
    workload_score: 88,
    bharat_ready_score: 93,
    hours_worked: 9.5,
    active_assignments: 2,
    status: 'active',
  },
  {
    id: 'v-21',
    name: 'Arun Kesarwani',
    age: 34,
    skills: ['protocol', 'information_desk', 'communication'],
    languages: ['hindi', 'english', 'urdu'],
    experience_level: 'intermediate',
    availability: 'available',
    assigned_zone: 'z-vip',
    workload_score: 33,
    bharat_ready_score: 73,
    hours_worked: 4.0,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-22',
    name: 'Meena Yadav',
    age: 30,
    skills: ['food_distribution', 'hygiene_management', 'first_aid'],
    languages: ['hindi', 'bhojpuri'],
    experience_level: 'intermediate',
    availability: 'available',
    assigned_zone: 'z-fd1',
    workload_score: 22,
    bharat_ready_score: 66,
    hours_worked: 2.5,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-23',
    name: 'Pankaj Shukla',
    age: 26,
    skills: ['traffic_coordination', 'vehicle_management', 'crowd_management'],
    languages: ['hindi', 'english'],
    experience_level: 'intermediate',
    availability: 'available',
    assigned_zone: 'z-g01',
    workload_score: 48,
    bharat_ready_score: 69,
    hours_worked: 6.0,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-24',
    name: 'Shreya Pandey',
    age: 23,
    skills: ['lost_and_found', 'information_desk', 'multilingual'],
    languages: ['hindi', 'english', 'nepali'],
    experience_level: 'beginner',
    availability: 'available',
    assigned_zone: 'z-lf1',
    workload_score: 14,
    bharat_ready_score: 58,
    hours_worked: 1.5,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-25',
    name: 'Abhishek Tripathi',
    age: 28,
    skills: ['security', 'crowd_management', 'emergency_response'],
    languages: ['hindi', 'bhojpuri'],
    experience_level: 'intermediate',
    availability: 'offline',
    workload_score: 60,
    bharat_ready_score: 77,
    hours_worked: 7.0,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-26',
    name: 'Rekha Soni',
    age: 45,
    skills: ['medical', 'nursing', 'first_aid', 'cpr'],
    languages: ['hindi', 'english'],
    experience_level: 'expert',
    availability: 'on_break',
    assigned_zone: 'z-mc2',
    workload_score: 75,
    bharat_ready_score: 87,
    hours_worked: 8.5,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-27',
    name: 'Gaurav Trivedi',
    age: 27,
    skills: ['traffic_coordination', 'vehicle_management'],
    languages: ['hindi'],
    experience_level: 'beginner',
    availability: 'available',
    workload_score: 5,
    bharat_ready_score: 43,
    hours_worked: 0.5,
    active_assignments: 0,
    status: 'active',
  },
  {
    id: 'v-28',
    name: 'Seema Chakraborty',
    age: 32,
    skills: ['information_desk', 'multilingual', 'communication', 'lost_and_found'],
    languages: ['hindi', 'english', 'bengali', 'assamese'],
    experience_level: 'expert',
    availability: 'available',
    assigned_zone: 'z-lf1',
    workload_score: 31,
    bharat_ready_score: 85,
    hours_worked: 4.0,
    active_assignments: 1,
    status: 'active',
  },
  {
    id: 'v-29',
    name: 'Rajiv Shankar',
    age: 50,
    skills: ['crowd_management', 'security', 'emergency_response', 'traffic_coordination'],
    languages: ['hindi', 'english'],
    experience_level: 'expert',
    availability: 'busy',
    assigned_zone: 'z-03',
    workload_score: 85,
    bharat_ready_score: 92,
    hours_worked: 9.0,
    active_assignments: 2,
    status: 'active',
  },
  {
    id: 'v-30',
    name: 'Tanya Singh',
    age: 24,
    skills: ['first_aid', 'cpr', 'nursing'],
    languages: ['hindi', 'english'],
    experience_level: 'beginner',
    availability: 'available',
    workload_score: 16,
    bharat_ready_score: 61,
    hours_worked: 2.0,
    active_assignments: 0,
    status: 'active',
  },
];

// ============================================================
// Demo Incidents
// ============================================================
export const DEMO_INCIDENTS: Incident[] = [
  {
    id: 'inc-01',
    zone_id: 'z-01',
    incident_type: 'Crowd Management',
    description: 'Overcrowding detected at Sangam Ghat main bathing area. Risk of stampede. Immediate crowd control required.',
    severity: 'critical',
    status: 'responding',
    volunteers_assigned: 6,
    ai_response_plan: 'Deploy crowd management team. Set up rope barriers. Activate backup.',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    zone: DEMO_ZONES[0],
  },
  {
    id: 'inc-02',
    zone_id: 'z-02',
    incident_type: 'Medical Emergency',
    description: 'Elderly pilgrim collapsed near Ram Ghat Gate 3. Suspected cardiac event. Crowd gathering.',
    severity: 'high',
    status: 'open',
    volunteers_assigned: 0,
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    zone: DEMO_ZONES[1],
  },
  {
    id: 'inc-03',
    zone_id: 'z-lf1',
    incident_type: 'Missing Person',
    description: '5-year-old child separated from family near Sangam entry. Speaks only Bhojpuri.',
    severity: 'high',
    status: 'open',
    volunteers_assigned: 2,
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
    zone: DEMO_ZONES[5],
  },
];

// ============================================================
// Demo Activity Feed
// ============================================================
export const DEMO_ACTIVITY: ActivityFeedItem[] = [
  {
    id: 'act-01',
    type: 'incident',
    title: 'Critical: Crowd surge at Sangam Ghat',
    description: 'Emergency response deployed. 6 volunteers en route.',
    zone: 'Sangam Ghat',
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    severity: 'critical',
  },
  {
    id: 'act-02',
    type: 'ai',
    title: 'AI rebalancing completed',
    description: 'Moved 3 volunteers from Medical Camp Beta to Medical Camp Alpha.',
    zone: 'Medical Camp Alpha',
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'act-03',
    type: 'assignment',
    title: 'Dr. Rajesh Sharma assigned',
    description: 'Assigned to Medical Camp Alpha for morning shift.',
    zone: 'Medical Camp Alpha',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'act-04',
    type: 'checkin',
    title: 'Col. Vijay Rawat checked in',
    description: 'Checked in at Sangam Ghat — BURNOUT RISK (91% workload)',
    zone: 'Sangam Ghat',
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    severity: 'high',
  },
  {
    id: 'act-05',
    type: 'incident',
    title: 'Missing child reported — Lost & Found',
    description: '5-year-old separated from family. Bhojpuri speaking.',
    zone: 'Lost & Found Center',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    severity: 'high',
  },
  {
    id: 'act-06',
    type: 'assignment',
    title: 'Ritu Agarwal assigned to Lost & Found',
    description: 'Multilingual expert deployed for missing child case.',
    zone: 'Lost & Found Center',
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: 'act-07',
    type: 'checkout',
    title: 'Ramesh Gupta on break',
    description: 'Workload 82% — scheduled break rotation.',
    zone: 'Ram Ghat',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: 'act-08',
    type: 'ai',
    title: 'AI Burnout alert: Dr. Sunita Tripathi',
    description: 'Workload score 88%. AI recommends immediate rotation.',
    zone: 'Medical Camp Alpha',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    severity: 'high',
  },
];

// ============================================================
// Demo Scenarios for Emergency Simulation
// ============================================================
export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    title: 'Medical Emergency — Ram Ghat',
    zone: 'Ram Ghat',
    zone_id: 'z-02',
    type: 'Medical Emergency',
    severity: 'critical',
    description:
      'Elderly pilgrim collapsed near Ram Ghat entry. Suspected cardiac event. Crowd gathering. Immediate medical response required.',
    volunteers_needed: 4,
  },
  {
    title: 'Crowd Crush Risk — Sangam Ghat',
    zone: 'Sangam Ghat',
    zone_id: 'z-01',
    type: 'Crowd Management',
    severity: 'high',
    description:
      'Overcrowding detected at main bathing ghat. Risk of stampede. Immediate crowd control and crowd management team needed.',
    volunteers_needed: 8,
  },
  {
    title: 'Missing Child — Lost & Found Center',
    zone: 'Lost & Found Center',
    zone_id: 'z-lf1',
    type: 'Missing Person',
    severity: 'high',
    description:
      '5-year-old child separated from family. Speaks only Bhojpuri. Last seen near Sangam entry gate. Requires multilingual volunteers.',
    volunteers_needed: 3,
  },
];

// ============================================================
// Utility: Calculate Bharat Ready Score
// ============================================================
export function calculateBharatReadyScore(volunteer: Volunteer): number {
  const skillScore = Math.min(volunteer.skills.length * 8, 40);
  const expScore = { beginner: 10, intermediate: 18, expert: 25 }[volunteer.experience_level] || 0;
  const availScore =
    { available: 15, on_break: 8, busy: 4, offline: 0 }[volunteer.availability] || 0;
  const langScore = Math.min(volunteer.languages.length * 5, 15);
  const workloadPenalty = volunteer.workload_score > 70 ? -10 : 0;
  return Math.min(100, Math.max(0, skillScore + expScore + availScore + langScore + workloadPenalty));
}

// ============================================================
// Utility: Get workload color
// ============================================================
export function getWorkloadColor(score: number): string {
  if (score <= 40) return '#16A34A';
  if (score <= 70) return '#D97706';
  if (score <= 85) return '#EA580C';
  return '#DC2626';
}

export function getWorkloadLabel(score: number): string {
  if (score <= 40) return 'Fresh';
  if (score <= 70) return 'Moderate';
  if (score <= 85) return 'Caution';
  return 'BURNOUT RISK';
}

export function getBRSLabel(score: number): string {
  if (score >= 80) return 'Combat Ready';
  if (score >= 60) return 'Deployment Ready';
  if (score >= 40) return 'Support Ready';
  return 'Needs Training';
}

export function getBRSColor(score: number): string {
  if (score >= 80) return '#16A34A';
  if (score >= 60) return '#D97706';
  if (score >= 40) return '#F59E0B';
  return '#9CA3AF';
}

export function getRiskColor(level: string): string {
  switch (level) {
    case 'critical': return '#DC2626';
    case 'high': return '#EA580C';
    case 'medium': return '#D97706';
    case 'low': return '#16A34A';
    default: return '#6B7280';
  }
}

export function getAvailabilityColor(status: string): string {
  switch (status) {
    case 'available': return '#16A34A';
    case 'busy': return '#EA580C';
    case 'on_break': return '#D97706';
    case 'offline': return '#6B7280';
    default: return '#6B7280';
  }
}
